{% set name = "dagster_bash" %}
{% set version = "0.6.7.post0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name|replace('_', '-') }}/{{ name|replace('_', '-') }}-{{ version }}.tar.gz"
  sha256: e06644be04967b10c695e0bea63478d44e17c65e5a577ca1f92bb4cdac6937bd

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - dagster {{ version }}.*

test:
  imports:
    - dagster_bash

about:
  home: "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-bash"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Package for Dagster bash solids."

extra:
  recipe-maintainers:
    - conda-forge/dagster
